on: [push]

jobs:
  proselint:
    runs-on: ubuntu-latest
    name: Proselint automation
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup proselint
        run: pip install proselint

      - name: Just run proselint
        shell: bash
        run: ${{ github.action_path }}/proselint *.md
