on: [push]

jobs:
  proselint:
    runs-on: ubuntu-latest
    name: Proselint automation
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
            python-version: 3.x

      - name: Setup and run proselint
        shell: bash
        run: | 
          python -m pip install --upgrade pip
          pip install proselint
          which proselint
          ls *.md
          tree
          proselint *.md
