on: [push]

jobs:
  proselint:
    runs-on: ubuntu-latest
    name: Proselint automation
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup python
        uses: actions/setup-python@v1

      - name: Setup proselint
        run: pip install --user proselint

      - name: Just run proselint
        shell: bash
        run: proselint README.md
